### ISSUE TITLE
Attribute error (Python exception: No attribute with the name caffe exists.)

### ISSUE THREAD

**Issue by RamRem28** [HomeOfVapourSynthEvolution/VapourSynth-Waifu2x-caffe#13]
I was testing different ways to upscale and waifu2xc-w2xc works fine but evaluating the script using waifu2x-caffe gives this error
```
Failed to evaluate the script:
Python exception: No attribute with the name caffe exists. Did you mistype a plugin namespace?

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1937, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1938, in vapoursynth.vpy_evaluateScript
File "C:/Users/ramgo/Desktop/waifu2x-caffe-inprogress.vpy", line 5, in 
clip = core.caffe.Waifu2x(clip, noise=0, scale=2, block_w=128, block_h=128, model=3, cudnn=False, processor=0, tta=False)
File "src\cython\vapoursynth.pyx", line 1523, in vapoursynth.Core.__getattr__
AttributeError: No attribute with the name caffe exists. Did you mistype a plugin namespace?

```
The script
```
import vapoursynth as vs
core = vs.get_core()
clip = core.ffms2.Source(source=r'H:\BackMedia\[Lazy Lily] Sono Hanabira ni Kuchizuke wo - Anata no Koibito Tsunagi OVA [1080p][MULTI][ED8FE413].mkv')
clip = core.fmtc.bitdepth (clip, bits=32)
clip = core.caffe.Waifu2x(clip, noise=1, scale=2, block_w=128, block_h=128, model=3, cudnn=True, processor=1, tta=False)
clip = core.fmtc.bitdepth (clip, bits=8)
clip.set_output()


# ffms2 and fmtc needed to run
# Bitdepth change is performed by fmtc.bitdepth to 32bit float input

```
Contents of the plugin directory:
```

    Directory: C:\Program Files (x86)\VapourSynth\plugins64


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       2018-10-14  23:21:16                models
-a----       2017-09-02   9:46:35       51670016 cublas64_90.dll
-a----       2017-09-02   9:46:45       48057344 curand64_90.dll
-a----       2016-12-29   7:35:41       13500928 ffms2.dll
-a----       2016-12-29   7:35:37          15154 ffms2.lib
-a----       2016-12-29   7:35:43         276992 ffmsindex.exe
-a----       2018-10-14   3:35:11        1206272 fmtconv.dll
-a----       2017-08-11  18:01:16        1343744 libiomp5md.dll
-a----       2017-08-11  18:01:18       21900032 svml_dispmd.dll
-a----       2017-02-23  21:39:34       14153728 vslsmashsource.dll
-a----       2017-11-09   9:00:33       90288128 Waifu2x-caffe.dll
```

**Comment by HolyWu** [comment]
You probably don't have the required cudnn64_7.dll which is mentioned in the README.

**Comment by RamRem28** [comment]
It appears to work now, I didn't realize that it wouldn't find it if I put it in C:/Windows/
